name: CMake

on: workflow_dispatch

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Build 
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      # working-directory: ~/XCVario
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      env:  
            AHRS_SECRET: ${{ secrets.AHRS_CIPHER_KEY }}
      run:  touch $PWD/main/Version.h;
            echo "#define CIPHER_KEY $AHRS_SECRET" >$PWD/main/cipher.h;
            # docker run --rm -v $PWD:/project -w /project espressif/idf idf.py build;
            #VER=`date +"%y.%m%d-%H%M"`;
            #cp $PWD/build/sensor.bin $PWD/images/sensor-${VER}.bin;
            git config user.name github-actions;
            git config user.email github-actions@github.com;
            #git checkout $PWD/main/cipher.h
            #git add $PWD/images/sensor-${VER}.bin;
            #git tag -a v${VER} -m "New XCVario build ${VER}";
            git commit -a -m "new version build sensor-${VER}.bin";
            git push;            

  
      
